# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sandeep Chayapathi
tagline:          '<something or the other>'
description:      'Personal ramblings fo Sandeep Chayapathi. '
url:              https://csandeep.github.io

author:
  name:           'Sandeep Chayapathi'
  url:            https://twitter.com/chayapathi

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/csandeep/csandeep.github.io
