# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sandeep Chayapathi
tagline:          '&lt;something or the other&gt;'
description:      'Personal blog of Sandeep Chayapathi'
url:              https://csandeep.github.io

author:
  name:           'Sandeep Chayapathi'
  url:            https://twitter.com/chayapathi

paginate:         5

# Custom vars
version:          1.0.0
gravatar_md5: eb2762c8b840daa8265c04e964deaf65

github:
  repo:           https://github.com/csandeep/csandeep.github.io

prose:
  rooturl: _posts
  siteurl: "https://csandeep.github.io"
  media: "img"
  metadata: 
    _posts: 
      - name: "layout"
        field:
          element: "select"
          label: "Type of post"
          options:
            - name: "Post"
              value: "post"
            - name: "Link"
              value: "link"
      - name: "link"
        field:
          element: "text"
          label: "Link"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Perl"
              value: "perl"
            - name: "Devops"
              value: "devops"
            - name: "Mac"
              value: "mac"
            - name: "Entertainment"
              value: "entertainment"
